// Fixed interface words (buttons, labels). Texts that differ per importer live in content/ and are edited in the admin screen.
export const UI = {
  en: {
    lang_name: "EN", home: "Home",
    nav_products: "Products", nav_check: "Check a pack", nav_doctors: "For doctors", nav_pharm: "For pharmacies", nav_contact: "Contact",
    search_ph: "Search a product, brand or ingredient", search_btn: "Search",
    hero_doc: "I am a doctor", hero_ph: "I run a pharmacy",
    brands_h: "Brands we import", featured_h: "Our products", view_all: "View all products",
    catalogue_h: "Product catalogue", catalogue_p: "Search by product, brand or ingredient.",
    catalogue_mrp: "Prices are the maximum retail price (MRP) printed on the pack, VAT included.",
    catalogue_desc: "All products imported and distributed by {company} in Bangladesh: composition, pack size, country of origin and retail price.",
    f_all: "All", f_brand: "All brands",
    count_one: "{n} product", count_many: "{n} products",
    empty: "No product matches that search. Try a shorter word, or clear the filters.", clear: "Clear filters",
    no_products: "Products will be listed here soon.",
    th_prod: "Product", th_comp: "Active composition", th_pack: "Pack", th_origin: "Origin",
    doc_btn: "Request literature",
    f_role: "I am a", r_pharm: "Pharmacy owner", r_doc: "Doctor", r_other: "Other",
    f_name: "Your name", f_org: "Pharmacy or chamber name", f_lic: "Drug licence no. (optional)", f_dist: "District", f_phone: "Mobile number",
    f_prods: "Products you are interested in", f_msg: "Message (optional)", f_submit: "Send inquiry",
    err: "Please fill in your name, district and a valid mobile number.",
    sending: "Sending…", sent_ok: "Thank you. Your inquiry has been sent and our sales team will call you.",
    sent_fail: "The inquiry could not be sent. Please copy it below and send it by WhatsApp or email.",
    out_h: "Your inquiry is ready", out_p: "Send it to our sales team on WhatsApp, or copy it into an email.",
    wa_btn: "Send on WhatsApp", copy: "Copy inquiry", copied: "Copied", copy_fail: "Select the text above and copy it",
    contact_h: "Contact", hotline: "Hotline", whatsapp: "WhatsApp", email: "Email", address: "Office",
    m_comp: "Composition", m_use: "How to use", m_pack: "Pack size", m_origin: "Made in", m_reg: "Registration no.", m_mrp: "MRP (incl. VAT)",
    m_buy: "Sold through pharmacies. Ask your pharmacist for this product by name.", m_ask: "Ask about this product",
    more_from: "More from {brand}", brand_products: "{brand} products in Bangladesh",
    brand_desc: "{brand} products from {country}, imported and distributed in Bangladesh by {company}.",
    cat_desc: "{category} imported and distributed in Bangladesh by {company}.",
    product_desc_tail: "Imported and distributed in Bangladesh by {company}.",
    imported_by: "Imported and distributed in Bangladesh by {company}.",
    nf_h: "Page not found", nf_p: "This page does not exist or has moved.", nf_btn: "Go to all products",
    rights: "All rights reserved."
  },
  bn: {
    lang_name: "বাংলা", home: "হোম",
    nav_products: "পণ্য", nav_check: "প্যাক যাচাই", nav_doctors: "চিকিৎসকদের জন্য", nav_pharm: "ফার্মেসির জন্য", nav_contact: "যোগাযোগ",
    search_ph: "পণ্য, ব্র্যান্ড বা উপাদান লিখে খুঁজুন", search_btn: "খুঁজুন",
    hero_doc: "আমি একজন চিকিৎসক", hero_ph: "আমার ফার্মেসি আছে",
    brands_h: "আমাদের আমদানি করা ব্র্যান্ড", featured_h: "আমাদের পণ্য", view_all: "সব পণ্য দেখুন",
    catalogue_h: "পণ্য তালিকা", catalogue_p: "পণ্য, ব্র্যান্ড বা উপাদান লিখে খুঁজুন।",
    catalogue_mrp: "এখানে দেখানো মূল্য প্যাকে ছাপানো সর্বোচ্চ খুচরা মূল্য (এমআরপি), ভ্যাটসহ।",
    catalogue_desc: "বাংলাদেশে {company}-এর আমদানি ও পরিবেশন করা সব পণ্য: উপাদান, প্যাকের পরিমাণ, উৎপাদনের দেশ ও খুচরা মূল্য।",
    f_all: "সব", f_brand: "সব ব্র্যান্ড",
    count_one: "{n}টি পণ্য", count_many: "{n}টি পণ্য",
    empty: "এই নামে কোনো পণ্য পাওয়া যায়নি। ছোট শব্দ দিয়ে খুঁজুন, অথবা ফিল্টার মুছে দিন।", clear: "ফিল্টার মুছুন",
    no_products: "পণ্যের তালিকা শিগগিরই এখানে যুক্ত হবে।",
    th_prod: "পণ্য", th_comp: "সক্রিয় উপাদান", th_pack: "প্যাক", th_origin: "উৎপাদনের দেশ",
    doc_btn: "লিটারেচার চেয়ে পাঠান",
    f_role: "আমি একজন", r_pharm: "ফার্মেসি মালিক", r_doc: "চিকিৎসক", r_other: "অন্যান্য",
    f_name: "আপনার নাম", f_org: "ফার্মেসি বা চেম্বারের নাম", f_lic: "ড্রাগ লাইসেন্স নম্বর (ঐচ্ছিক)", f_dist: "জেলা", f_phone: "মোবাইল নম্বর",
    f_prods: "যেসব পণ্যে আগ্রহী", f_msg: "বার্তা (ঐচ্ছিক)", f_submit: "অনুসন্ধান পাঠান",
    err: "আপনার নাম, জেলা ও সঠিক মোবাইল নম্বর লিখুন।",
    sending: "পাঠানো হচ্ছে…", sent_ok: "ধন্যবাদ। আপনার অনুসন্ধান পাঠানো হয়েছে, আমাদের সেলস টিম আপনাকে ফোন করবে।",
    sent_fail: "অনুসন্ধানটি পাঠানো যায়নি। নিচের লেখাটি কপি করে হোয়াটসঅ্যাপ বা ইমেইলে পাঠান।",
    out_h: "আপনার অনুসন্ধান তৈরি হয়েছে", out_p: "হোয়াটসঅ্যাপে আমাদের সেলস টিমকে পাঠান, অথবা কপি করে ইমেইল করুন।",
    wa_btn: "হোয়াটসঅ্যাপে পাঠান", copy: "অনুসন্ধান কপি করুন", copied: "কপি হয়েছে", copy_fail: "উপরের লেখাটি সিলেক্ট করে কপি করুন",
    contact_h: "যোগাযোগ", hotline: "হটলাইন", whatsapp: "হোয়াটসঅ্যাপ", email: "ইমেইল", address: "অফিস",
    m_comp: "উপাদান", m_use: "ব্যবহারবিধি", m_pack: "প্যাকের পরিমাণ", m_origin: "উৎপাদনের দেশ", m_reg: "নিবন্ধন নম্বর", m_mrp: "এমআরপি (ভ্যাটসহ)",
    m_buy: "ফার্মেসিতে পাওয়া যায়। ফার্মাসিস্টকে পণ্যের নাম বলে চেয়ে নিন।", m_ask: "এই পণ্য সম্পর্কে জানতে চান",
    more_from: "{brand}-এর আরও পণ্য", brand_products: "বাংলাদেশে {brand}-এর পণ্য",
    brand_desc: "{country}-এর {brand} ব্র্যান্ডের পণ্য, বাংলাদেশে আমদানি ও পরিবেশন করে {company}।",
    cat_desc: "{category}: বাংলাদেশে আমদানি ও পরিবেশন করে {company}।",
    product_desc_tail: "বাংলাদেশে আমদানি ও পরিবেশন করে {company}।",
    imported_by: "বাংলাদেশে আমদানি ও পরিবেশন করে {company}।",
    nf_h: "পাতাটি পাওয়া যায়নি", nf_p: "এই পাতাটি নেই অথবা সরিয়ে নেওয়া হয়েছে।", nf_btn: "সব পণ্য দেখুন",
    rights: "সর্বস্বত্ব সংরক্ষিত।"
  }
};
